const PeerComparisonStyles = {
  card: {
    display: "flex",
    flexDirection: "column",
    alignContent: "flex-end",
    width: "90%",
    margin: "auto",
    textAlign: "left",
    padding: 0,
    marginTop: 24,
    borderRadius: 12,
    marginBottom: 18,
  },
  section: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-start",
    width: "100%",
    marginTop: -10,
    marginBottom: -5,
  },
  button: {
    display: "inline-block",
    letterSpacing: "0.125em",
    color: "blue",
    backgroundColor: "white",
    borderColor: "hsl(243,93%,67%)",
    borderWidth: 1,
    width: 250,
    fontSize: 14,
    marginRight: 14,
    borderRadius: 6,
    fontWeight: 500,
    fontStyle: "normal",
  },
  columnsIcon: {
    display: "flex",
    flexDirection: "row",
    alignContent: "center",
    justifyContent: "center",
  },
  refineryWord: {
    color: "blue",
    letterSpacing: 0.5,
  },
  input: {
    height: 30,
    borderRadius: 8,
    borderColor: "grey",
    borderWidth: 1.5,
    marginTop: 16,
    marginLeft: 16,
    padding: 14,
    fontSize: 14,
    display: "inline",
  },
  "@media all and (max-width:768px)": {
    newSection: {
      flexDirection: "column",
      justifyContent: "",
    },
    button: {
      height: 40,
      width: 200,
      fontSize: 12,
    },
  },
};
export default PeerComparisonStyles;
